name: ecology-core
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-bio
  - dendropy
  - biom-format
  - tqdm
  - pytest
  - pip:
    - -e .  # Install package in development mode